任务:基于flare文本数据，建立LSTM模型，预测序列文字:
1.完成数据预处理，将文字序列数据转化为可用于LSTM输入的数据
2.查看文字数据预处理后的数据结构，并进行数据分离操作
3.针对字符串输入(” flare is a teacher in ai industry. He obtained his phd in Australia.”)，预测其对应的后续字符备注:模型结构:单层LSTM，输出有20个神经元;每次使用前20个字符预测第21个字符

In [28]:
#load the data
data = open('flare').read()
data = data.replace('\n', ' ').replace('\r', ' ')
print(data)

flare is a teacher in ai industry.He obtained his phd in Australia. Australia is a country in the Southern Hemisphere. flare is a teacher in ai industry.He obtained his phd in Australia. Australia is a country in the Southern Hemisphere. flare is a teacher in ai industry.He obtained his phd in Australia. Australia is a country in the Southern Hemisphere. flare is a teacher in ai industry.He obtained his phd in Australia. Australia is a country in the Southern Hemisphere. flare is a teacher in ai industry.He obtained his phd in Australia. Australia is a country in the Southern Hemisphere. flare is a teacher in ai industry.He obtained his phd in Australia. Australia is a country in the Southern Hemisphere. flare is a teacher in ai industry.He obtained his phd in Australia. Australia is a country in the Southern Hemisphere. flare is a teacher in ai industry.He obtained his phd in Australia. Australia is a country in the Southern Hemisphere. flare is a teacher in ai industry.He obtained hi

In [29]:
#字符去重处理
letters = list(set(data))
print(letters)
num_letters = len(letters)
print(num_letters)

['A', 'f', 'c', 'n', 'i', 'u', 'a', 'e', 't', 'r', ' ', 'm', 'H', 'l', 's', 'd', '.', 'b', 'h', 'S', 'o', 'p', 'y']
23


In [30]:
#建立字典
int2char = {i:c for i, c in enumerate(letters)}
print(int2char)

{0: 'A', 1: 'f', 2: 'c', 3: 'n', 4: 'i', 5: 'u', 6: 'a', 7: 'e', 8: 't', 9: 'r', 10: ' ', 11: 'm', 12: 'H', 13: 'l', 14: 's', 15: 'd', 16: '.', 17: 'b', 18: 'h', 19: 'S', 20: 'o', 21: 'p', 22: 'y'}


In [31]:
char2int = {c:i for i, c in enumerate(letters)}
print(char2int)

{'A': 0, 'f': 1, 'c': 2, 'n': 3, 'i': 4, 'u': 5, 'a': 6, 'e': 7, 't': 8, 'r': 9, ' ': 10, 'm': 11, 'H': 12, 'l': 13, 's': 14, 'd': 15, '.': 16, 'b': 17, 'h': 18, 'S': 19, 'o': 20, 'p': 21, 'y': 22}


In [32]:
from tkinter import Y
import numpy as np
from keras.utils import to_categorical

def extract_data(data, slide):
    x = []
    y = []
    for i  in range(0, len(data) - slide):
        x.append([a for a in data[i:i+slide]])
        y.append(data[i+slide])
    return x, y


def char2int_Data(x, y, char_to_int):
    x_int = []
    y_int = []
    for i in range(len(x)):
        x_int.append([char_to_int[cha] for cha in x[i]])
        y_int.append([char_to_int[cha] for cha in y[i]])
    return x_int, y_int

def data_preprocess(data, slide, num_letters, char_to_int):
    char_Data = extract_data(data, slide)
    int_Data = char2int_Data(char_Data[0], char_Data[1], char_to_int)
    input = int_Data[0]
    output = list(np.array(int_Data[1]).flatten())
    input_data_reshaped = np.array(input).reshape(len(input), slide)
    new = np.random.randint(0, 10, size=[input_data_reshaped.shape[0], input_data_reshaped.shape[1], num_letters])
    for i in range(input_data_reshaped.shape[0]):
        for j in range(input_data_reshaped.shape[1]):
            new[i,j,:] = to_categorical(input_data_reshaped[i,j], num_classes=num_letters)
    
    return new, output

In [33]:
#define x and y
time_steps = 20
x, y = data_preprocess(data, time_steps, num_letters, char2int)
print(x.shape, len(y))

(118980, 20, 23) 118980


In [34]:
print(x)

[[[0 1 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 ...

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 1 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 1 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]]


In [35]:
#分离数据
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.1, random_state=10)
print(x_train.shape, len(y_train))    

(107082, 20, 23) 107082


In [36]:
y_train_category = to_categorical(y_train, num_letters)
print(y_train_category)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 1. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [37]:
#建立模型
from os import access
from keras.models import Sequential
from keras.layers import LSTM, Dense
from torch import mode

model = Sequential()
model.add(LSTM(units=20, input_shape=(x_train.shape[1], x_train.shape[2]), activation='relu'))
#输出层 多分类
model.add(Dense(units=num_letters, activation='softmax'))
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])
model.summary()

/usr/local/lib/python3.11/site-packages/keras/src/layers/rnn/rnn.py:200: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ lstm_1 (LSTM)                   │ (None, 20)             │         3,520 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 23)             │           483 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 4,003 (15.64 KB)

 Trainable params: 4,003 (15.64 KB)

 Non-trainable params: 0 (0.00 B)

In [50]:
#训练模型
model.fit(x_train, y_train_category, epochs=5, batch_size=1000)


Epoch 1/5
108/108 ━━━━━━━━━━━━━━━━━━━━ 3s 29ms/step - accuracy: 0.9150 - loss: 0.3455
Epoch 2/5
108/108 ━━━━━━━━━━━━━━━━━━━━ 3s 30ms/step - accuracy: 1.0000 - loss: 0.0332
Epoch 3/5
108/108 ━━━━━━━━━━━━━━━━━━━━ 3s 31ms/step - accuracy: 1.0000 - loss: 0.0146
Epoch 4/5
108/108 ━━━━━━━━━━━━━━━━━━━━ 3s 31ms/step - accuracy: 1.0000 - loss: 0.0084
Epoch 5/5
108/108 ━━━━━━━━━━━━━━━━━━━━ 5s 32ms/step - accuracy: 1.0000 - loss: 0.0055


In [ ]:
#预测
y_train_predict = model.predict(x_train)
y_train_predict = np.round(y_train_predict).astype(int)
print(y_train_predict)

3347/3347 ━━━━━━━━━━━━━━━━━━━━ 9s 3ms/step
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 1 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


In [44]:
#one hot 转换
labels = np.argmax(y_train_predict, axis=1)
print(labels)
y_train_predict_char = [int2char[i] for i in labels]
print(y_train_predict_char)

[ 4 18 20 ...  9  4 14]
['i', 'h', 'o', ' ', 'd', 'a', 'a', 'A', ' ', 'h', 't', 'A', 'l', 'i', ' ', 'i', 'A', 'o', 't', 'A', 'A', 'u', 't', 'l', 's', ' ', 'A', 'r', 't', 'A', 'a', 'n', 't', 's', ' ', ' ', 'A', ' ', ' ', ' ', ' ', '.', 'n', 's', 'A', 'A', 'e', 's', 'A', 'e', 'u', ' ', 'i', ' ', 'l', 'h', 'i', 'A', ' ', 'd', 'u', 'i', 's', ' ', ' ', 'A', 'u', 'e', 'a', 'i', 'i', 'A', 'i', 'n', 'r', 'A', ' ', 'e', ' ', 's', 'a', 'e', 'i', ' ', 'A', 'e', 'u', 'e', 't', 'i', ' ', 'l', 'e', 'u', 's', '.', ' ', 'i', ' ', 'i', 't', 't', ' ', ' ', 't', 'A', ' ', 'A', ' ', 'A', 'l', 'l', ' ', 'A', ' ', 'a', 'o', 'r', 't', 'u', 'A', ' ', 'e', 'n', '.', 'A', 'A', 'n', 'h', 'A', 'i', 'b', ' ', 'i', 'e', 'p', 'a', 't', 'A', 'A', 'A', 'u', 'A', 'n', 't', 'a', 'e', 'A', 'r', 'i', 'r', 't', 'i', 'A', 'A', 'u', ' ', '.', 'r', 's', ' ', 'a', 'p', 'r', 'h', 'i', 'A', 'A', 'A', 'i', 'A', 'A', 'l', 'a', 'l', 't', 'A', ' ', 'n', 't', 'A', 'A', 'a', ' ', 'a', 'a', 's', 'u', ' ', ' ', 'a', 'e', 'A', 'l', 'A', 

In [46]:
from sklearn.metrics import accuracy_score
accuracy_train = accuracy_score(y_train, labels)
print("训练集准确率：", accuracy_train)

训练集准确率： 0.7305616256700472


In [52]:
#预测
y_test_predict = model.predict(x_test)
y_test_predict = np.round(y_test_predict).astype(int)
print(y_test_predict)
labels = np.argmax(y_test_predict, axis=1)
print(labels)
accuracy_test = accuracy_score(y_test, labels)
print("测试集准确率：", accuracy_test)

372/372 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 1 0 0]]
[ 9 18  5 ...  3  6 20]
测试集准确率： 1.0


In [53]:
new_letters = 'flare is a teacher in ai industry. He obtained his phd in Australia.'
x_new, y_new = data_preprocess(new_letters, time_steps, num_letters, char2int)
y_new_predict = model.predict(x_new)
y_new_predict = np.round(y_new_predict).astype(int)
labels = np.argmax(y_new_predict, axis=1)
y_new_predict_char = [int2char[i] for i in labels]
print(y_new_predict_char)

2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step
['n', ' ', 'a', 'i', ' ', 'i', 'n', 'd', 'u', 's', 't', 'r', 'y', '.', 'H', 'e', 'e', 'o', 'o', 'u', 't', 'a', 'i', 'n', 'e', 'd', ' ', 't', 'e', 's', ' ', 'p', 'h', 'd', ' ', 'i', 'n', ' ', 'A', 'u', 's', 't', 'r', 'a', 'l', 'i', 'a', '.']


In [ ]:
for i in range(0, x_new.shape[0]-20):
    print(''.join(new_letters[i:i+20]), '->', y_new_predict_char[i])